### PR TITLE
GitHub Action to lint Python code

### PR DESCRIPTION
**Pull request by cclauss**
Because Travis CI seems to be on (permanent?) vacation.
* https://travis-ci.org/github/ilevkivskyi/com2ann/builds

Results: https://github.com/cclauss/com2ann/actions

### CODE REVIEW

**Comment by ilevkivskyi** [comment]
Thank you! Hm, I think maybe we can try use travis-ci.com instead of travis-ci.org (as the banner says). Let me try update the repo configs. (I will probably merge this PR anyway later).

**Review by ilevkivskyi — APPROVED** [review]

**Comment by ilevkivskyi** [comment]
Yep, as you can see the build is running on Travis again.

**Comment by cclauss** [comment]
Does https://app.travis-ci.com/github/ilevkivskyi/com2ann/pull_requests work?

**Comment by ilevkivskyi** [comment]
Hm, wait actually something is weird with Travis. Anyway, at least the action works well.

**Comment by ilevkivskyi** [comment]
OK, I managed to fix it. Travis should work on master from the next request.

**Pull request merged**
